<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <UserSecretsId>a2acf53a-e45c-41f0-8de5-661ec0bbfca4</UserSecretsId>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>




  <ItemGroup>
    <Content Include="Properties\launchSettings.json" />
  </ItemGroup>




  <ItemGroup>
    <ProjectReference Include="..\CommerceCore.Ordering.Application\CommerceCore.Ordering.Application.csproj" />
    <ProjectReference Include="..\CommerceCore.Ordering.Infrastructure\CommerceCore.Ordering.Infrastructure.csproj" />
  </ItemGroup>

</Project>
