<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommerceCore.Ordering.Application\CommerceCore.Ordering.Application.csproj" />
    <ProjectReference Include="..\CommerceCore.Ordering.Domain\CommerceCore.Ordering.Domain.csproj" />
  </ItemGroup>

</Project>
